apiVersion: v1
kind: Service
metadata:
  labels:
    app: nest-react-blog-marc-mongodb
  name: nest-react-blog-marc-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: nest-react-blog-marc-mongodb