apiVersion: v1
kind: Pod
metadata:
  name: nest-react-blog-marc-mongodb
  labels:
    app: nest-react-blog-marc-mongodb
spec:
  volumes:
  - name: nest-react-blog-marc-mongo-vol
    persistentVolumeClaim:
      claimName: nest-react-blog-marc-pvc
  containers:
  - image: mongo
    name: container
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: nest-react-blog-marc-mongo-vol
      mountPath: /data/db