apiVersion: v1
kind: Service
metadata:
  name: nest-react-blog-marc-server-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: nest-react-blog-marc-server
  type: LoadBalancer