kind: Deployment
apiVersion: apps/v1
metadata:
  name: nest-react-blog-marc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-react-blog-marc
  template:
    metadata:
      labels:
        app: nest-react-blog-marc
    spec:
      containers:
        - name: nest-react-blog-marc
          image: localhost:5000/nest-react-blog-marc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: nest-react-blog-marc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: nest-react-blog-marc