export const LOCAL_AUTH_STRATEGY_NAME = 'LOCAL';
export const JWT_AUTH_STRATEGY_NAME = 'JWT';
export const MONGO_SERVER_NAME = 'MONGODB';
export const VALID_AUTH_STRATEGY_NAMES: string[] =  [LOCAL_AUTH_STRATEGY_NAME, JWT_AUTH_STRATEGY_NAME];
export const VALID_DATA_SERVER_NAMES: string[] =  [MONGO_SERVER_NAME];
export const ENV_PROD_DIRECTORY = './';
